### ISSUE TITLE
Can't create citation in APA style for journal articles

### ISSUE THREAD

**Issue by weirdf0x** [citeproc-py/citeproc-py#146]
Got APA CSL-file from Zotero: https://www.zotero.org/styles/apa

```python
from citeproc import (
    Citation,
    CitationItem,
    CitationStylesBibliography,
    CitationStylesStyle,
    formatter,
)
from citeproc.source.json import CiteProcJSON


def run():
    pub = {
        "id": "2656243/9G79BL7D",
        "type": "article-journal",
        "title": "Some Notes on Gertrude Stein and Deixis",
        "container-title": "Arizona Quarterly: A Journal of American Literature, Culture, and Theory",
        "page": "91-102",
        "volume": "53",
        "issue": "1",
        "URL": "https://muse-jhu-edu.pitt.idm.oclc.org/article/445403/pdf",
        "DOI": "10.1353/arq.1997.0020",
        "author": [{"family": "Cook", "given": "Albert"}],
        "issued": {"date-parts": [[1997]]},
    }

    bib_source = CiteProcJSON([pub])
    bib_style = CitationStylesStyle("./apa.csl", validate=False)
    bibliography = CitationStylesBibliography(bib_style, bib_source, formatter.plain)

    citation = Citation([CitationItem("2656243/9G79BL7D")])

    bibliography.register(citation)

    def warn(citation_item):
        print(
            "WARNING: Reference with key '{}' not found in the bibliography.".format(
                citation_item.key
            )
        )

    items = bibliography.bibliography()
    print(items)


if __name__ == "__main__":
    run()

```
Can't get any citation to work with this style though. I always get:
```
AttributeError: 'NoneType' object has no attribute 'single'
```
in https://github.com/citeproc-py/citeproc-py/blob/v0.6.0/citeproc/model.py#L1329

`variable` is set to `part-number` (weird for journal articles?) and `term` is `None`

Any ideas what's causing the problem or where to look?

**Comment by bhushan-mohanraj** [comment]
I'm not sure, but the error message looks the same as #145.

**Comment by zepinglee** [comment]
This is because the `part-number` term is missing in `citeproc/data/locales/locales-en-US.xml`. I suggest `if not term: return None`.

**Comment by congtailai** [comment]
Still not working using the latest csl version. 

Try using an older csl version (newest working version):
[https://raw.githubusercontent.com/citation-style-language/styles/38bc5feb0f3ac7b3cf12281168aac8e53bba5085/apa.csl](https://raw.githubusercontent.com/citation-style-language/styles/38bc5feb0f3ac7b3cf12281168aac8e53bba5085/apa.csl)

**Comment by danielopitz** [comment]
In the meantime we started using the original Haskell citeproc as a binary, but thanks for the hint.

**Comment by yarikoptic** [comment]
I think master has that issue addressed!

```
❯ git describe
v0.8.2-14-g2aeb250
❯ python -c 'from duecredit.io import format_bibtex, import_doi, BibTeX; print(format_bibtex(BibTeX(import_doi("https://doi.org/10.1039/C8LC00458G")), style="/tmp/apa7.csl"))'
Olanrewaju, A., Beaugrand, M., Yafia, M., & Juncker, D.. (2018). Capillary microfluidics in microchannels: from microfluidic networks to capillaric circuits. Lab on a Chip, 18(16), 2323–2347. https://doi.org/10.1039/c8lc00458g
```

<details>
<summary>while released 0.8.2 still fails</summary> 

```shell
❯ git co v0.8.2
M	citeproc/data/schema
Note: switching to 'v0.8.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at c71f0a5 Update CHANGELOG.md [skip ci]
❯ python -c 'from duecredit.io import format_bibtex, import_doi, BibTeX; print(format_bibtex(BibTeX(import_doi("https://doi.org/10.1039/C8LC00458G")), style="/tmp/apa7.csl"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from duecredit.io import format_bibtex, import_doi, BibTeX; print(format_bibtex(BibTeX(import_doi("https://doi.org/10.1039/C8LC00458G")), style="/tmp/apa7.csl"))
                                                                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/duecredit/io.py", line 368, in format_bibtex
    biblio_out = bibliography.bibliography()
  File "/home/yoh/proj/misc/citeproc-py/citeproc/frontend.py", line 101, in bibliography
...
  File "/home/yoh/proj/misc/citeproc-py/citeproc/model.py", line 1383, in process
    child_text = child.render(item, context=context, **kwargs)
  File "/home/yoh/proj/misc/citeproc-py/citeproc/model.py", line 95, in render
    return self.markup(self.process(*args, **kwargs))
                       ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/yoh/proj/misc/citeproc-py/citeproc/model.py", line 1344, in process
    text = term.single
           ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'single'

```
</details>

**We need to release!**

**Comment by tmorrell** [comment]
Now works with release v0.8.3
